### ISSUE TITLE
Event::Moved isn't working

### ISSUE THREAD

**Issue by darkstalker** [tomaka/glutin#724] opened 2016-02-15 18:12 UTC
Moving the window around isn't triggering Event::Moved. Tested with glutin 0.4.8 under Linux/X11 and OSX.

test code: https://gist.github.com/darkstalker/d83872cea9d828a591d6

**Comment by vberger** [comment] 2016-02-16 08:37
Just as a side note: this won't be fixeable for the wayland backend. By design wayland client do not know nor control the location of their windows on the screen.

**Comment by tomaka** [comment] 2016-11-03 08:06
Closing for https://github.com/tomaka/winit/issues/67

**Closed by tomaka** 2016-11-03 08:06 UTC
Labels: bug
