### ISSUE TITLE
NoAvailablePixelFormat error

### ISSUE THREAD

**Issue by gheoan** [tomaka/glutin#913] opened 2017-07-20 00:16 UTC
Running the `window` example on Windows 10, with Intel GMA X4500 GPU results in error `NoAvailablePixelFormat` at `.\examples/window.rs:11`. Glutin version is 0.9.1. Is it possible to configure the context to support this GPU? Let me know if more information is needed.

**Comment by jrmiller82** [comment] 2017-07-20 18:51
Try commenting out the `.with_multisampling(x);` line in your rust file. You'll lose antialiasing, but that should work. Don't forget to add a terminal semicolon to the line above if your commenting out the other line changes the semicolon flow. 

But, yes, this is definitely a bug, glutin needs to check if the underlying system's OpenGL is high enough version to support the features called by glutin.

**Comment by jrmiller82** [comment] 2017-07-20 19:16
Devs, I have this same issue on Debian unstable on an older Lenovo Thinkpad x201, as well as on an Ubuntu 17.04 system running on a virtualbox VM.

**Comment by gheoan** [comment] 2017-07-20 21:10
This is not neccesary a bug. I do not expect glutin to support a GPU with OpenGL version 1.1 (Intel GMA X4500). However, the error is not very descriptive and there is no documentation regarding minimum supported OpenGL version.

**Comment by jrmiller82** [comment] 2017-07-20 21:20
`% glxinfo | grep "version"
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 3.3
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.0
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.0.3
OpenGL core profile shading language version string: 3.30
OpenGL version string: 3.0 Mesa 17.0.3
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 17.0.3
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
`

Here's the output from my virtualbox machine. Looking like max core is 3.3. Not 1.1.

**Comment by tomaka** [comment] 2017-07-21 06:20
The error is not a matter of supported OpenGL version.
Glutin queries the system for the configuration you request (multisampling, sRGB, depth buffer size, etc.) and if the system doesn't support this configuration, then `NoAvailablePixelFormat` is returned.

**Comment by lo48576** [comment] 2017-08-10 02:48
Same error occured in my environment (gentoo linux amd64) with `gfx_device_gl` and `gfx_window_glutin` crates and `glutin::GlProfile::Core`, `gfx::format::Srgba8` and `gfx::format::DepthStencil` config.

The error happened with [mesa-17.2.0_rc3](https://lists.freedesktop.org/archives/mesa-dev/2017-August/165750.html) but doesn't happened with [mesa-17.1.6](https://mesa3d.org/relnotes/17.1.6.html) or older versions.

**Comment by C-Bouthoorn** [comment] 2017-09-11 17:00
This issue also appears on Linux (Antergos - Arch based)

```
$ glxinfo | grep "version"
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.2.0
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 17.2.0
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 17.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

GPU is Nvidia GTX 1050. This error seems to have happened after updating mesa from `17.1.8-1` to `17.1.8-2`. Also  the most recent version of `17.2.0-2` gives this error.

Also see https://github.com/PistonDevelopers/piston/issues/1202 for more details.

**Comment by stevebob** [comment] 2017-09-16 13:14
I'm having the same issue on archlinux on a macbook air with intel integrated graphics. Downgrading mesa from `17.2.0-2` to `17.1.8-1` is my temporary workaround.

**Comment by lolzballs** [comment] 2017-09-19 01:59
I'm having the same issue on both Intel HD Graphics 630 and GTX 1050 via bumblebee.
GTX 1050 directly with proprietary drivers works however.

I'm running Arch with `mesa 17.2.0-2`.

**Comment by C-Bouthoorn** [comment] 2017-09-21 17:20
**Update:** Still the case with `mesa-17.2.1-3`, `glutin v0.9.2` and [updated subdependencies](https://gist.github.com/C-Bouthoorn/b899e0002711108a698bfc8da35ece83).

**Comment by norru** [comment] 2017-10-08 23:09
Mee Too!™

Just got this on Devuan Ceres, Lenovo Thinkpad X1 (Intel 520), rust 1.22.0-nightly, glutin 0.10.0. I have resumed work on my gfx "demo" and just managed to port and run from rust 1.12. As it stands, this is a showstopper.

**Comment by norru** [comment] 2017-10-09 23:31
It is Srgb's fault. Commenting out the "does not work" line below reproduces the error. As a result I had to replace all Srgba8 pixelformats in my gfx calls to Rgba8 - perhaps one for @kvark and do the gamma correction in the tonemapper's fragment program.

```
	const WIDTH: u32 = 1024;
	const HEIGHT: u32 = 1024;

	let mut events_loop = glutin::EventsLoop::new();

	let builder = glutin::WindowBuilder::new()
		.with_title("Box2d + GFX".to_string())
		.with_dimensions(WIDTH, HEIGHT);

	let context_builder = glutin::ContextBuilder::new()
		//.with_srgb(true) <--- does not work
		.with_gl(glutin::GlRequest::Latest)
		.with_gl_robustness(glutin::Robustness::TryRobustNoResetNotification)
		.with_gl_profile(glutin::GlProfile::Core)
		.with_multisampling(1)
		.with_depth_buffer(24u8)
		.with_stencil_buffer(8u8)
		.with_pixel_format(24u8, 0u8)
		.with_vsync(true);


	let window = glutin::GlWindow::new(builder, context_builder, &events_loop).unwrap();
```

**Comment by lo48576** [comment] 2017-10-10 07:24
FYI: [102354 – Mesa 17.2 no longer can give SRGB-capable framebuffer on i965, even though Mesa 17.1.x does.](https://bugs.freedesktop.org/show_bug.cgi?id=102354) seems causing this issue.
(I'm sorry if I am wrong).

**Comment by rivertam** [comment] 2017-11-11 17:18
I'm not sure exactly what's happening, but with mesa 17.4.0-devel and 17.3.0-devel, this issue is still occurring despite indications that it should be fixed on master (which I believe is currently 17.3.0; versions are confusing me because oibaf has 17.4.0 available while mesa's website only has 17.3.0. Both have been updated since the patch should have gone out, as far as I can tell). `.with_srbg(true)` does not fix the issue for me. I'm unclear on how to downgrade mesa safely, so I'm probably going to hold off until mesa resolves the issue on newer, accessible packages, unless someone has any guidance for me.

`glxinfo | rg opengl` yields:

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.4.0-devel
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.4.0-devel
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 17.4.0-devel
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by C-Bouthoorn** [comment] 2018-05-02 16:35
This issue seems to be fixed with the latest `mesa 18.*`. Please see https://github.com/PistonDevelopers/piston/issues/1202 for more information

**Comment by fasihrana** [comment] 2018-10-15 12:56
I'm working on a webrender based GUI framework and I get this error when executing the program via a remotedesktop connection. Might this issue be causing the same error for me which is `NoAvailablePixelFormat` ?

**Comment by ZeGentzy** [comment] 2019-02-25 23:46
@gheoan @fasihrana  See https://github.com/tomaka/glutin/issues/952#issuecomment-467228004

**Closed by ZeGentzy** 2019-02-25 23:46 UTC
Labels: To-Closed-For-Inactivity, platform: X11, type: bug

**Comment by RpxdYTX** [comment] 2021-11-30 02:21
Getting this error on windows 8.1 when trying to use `ContextBuilder::new ().build_windowed (/* ... */)`

**Comment by maroider** [comment] 2021-11-30 02:32
Is this a native windows installation or is it running in a VM?

**Comment by RpxdYTX** [comment] 2021-11-30 18:17
I am not sure, it seems native, but the performance is significantly better than before, it also contains an installation of Oracle's VM

I am not sure because the computer broke and i brought it to someone that could fix it, when it came, it was with Oracle VirtualBox installed.

**Comment by RpxdYTX** [comment] 2021-11-30 21:39
I tried running msinfo32 but nothing about VMs appeared, so i guess i am in native

**Comment by RpxdYTX** [comment] 2021-12-01 00:43
Also, using the crate glfw and gl_loader worked for me, i used a macro to transmute the pointer to a function pointer, not only did everything work, but I was even able to use a nice blue color in a basic window
