### ISSUE TITLE
AppKit not being called from main thread

### ISSUE THREAD

**Issue by adudney** [tomaka/glutin#245] opened 2015-02-01 09:13 UTC
I'm not sure how to handle this in a cross platform manner, but calling any AppKit method on a background thread is disallowed and undefined behavior (And Glium uses exclusively that)

Note: I'm posting this to both Glium and Glutin's pages, as I'm not sure where it's best to solve this.

https://github.com/tomaka/glium/issues/425

**Comment by tomaka** [comment] 2015-02-01 17:04
Yeah that's a big problem.

If it can't be enforced at compile-time, it should at least be enforced at runtime.

**Comment by bobakker** [comment] 2015-02-01 19:16
So, is this the reason we've been getting spinning beachballs of death if we run the Glium examples on OS X?

**Comment by tomaka** [comment] 2015-02-01 19:21
Probably :-/

**Comment by camjackson** [comment] 2015-02-01 20:52
But the bug isn't in the example code is it? It's built into way glium's
message loop works, right? Hope it's not too annoying to change, just for
osx.

**Comment by tomaka** [comment] 2015-02-01 21:24
Glium does something wrong, but the problem is that glutin lets you do that wrong thing without any compile-time error nor panic.

**Comment by SSheldon** [comment] 2015-05-16 16:05
Any thoughts on how to solve this? In #4 there was mention of [a macro solution](https://github.com/tomaka/glutin/issues/4#issuecomment-52153363).

The issue of accessing things off the main thread could be resolved by dispatching more work to the main thread, but it feels like there's a fundamental difference between how Cocoa works and the other APIs. Unless we enforce that all glutin apps call a `glutin_main`, there'll have to be different instructions for using it on OSX vs other platforms.

**Comment by SSheldon** [comment] 2015-05-16 16:08
This issue relates to #47 and may be a dup.

**Comment by tomaka** [comment] 2015-05-16 16:11
Yeah let's close this in favor of #47

**Closed by tomaka** 2015-05-16 16:11 UTC
Labels: A-cocoa
