### ISSUE TITLE
example in the readme doesn't compile on Rust 1.7

### ISSUE THREAD

**Issue by Jayflux** [tomaka/glutin#776] opened 2016-05-16 13:38 UTC
```
MC-S104347:glut willij87$ rustc --version
rustc 1.7.0
```

```
MC-S104347:glut willij87$ cargo build
   Compiling xml-rs v0.3.3
   Compiling cocoa v0.3.4
<bitflags macros>:89:15: 90:32 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:89  # [ inline ] fn bitor_assign ( & mut self , other : $ BitFlags ) {
<bitflags macros>:90 self . bits |= other . bits ; } } impl $ crate:: __core:: ops:: BitXor for $
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:86:59: 87:18 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:86 $ BitFlags { bits : self . bits | other . bits } } } impl $ crate:: __core::
<bitflags macros>:87 ops:: BitOrAssign for $ BitFlags {
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:98:15: 99:32 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:98  # [ inline ] fn bitxor_assign ( & mut self , other : $ BitFlags ) {
<bitflags macros>:99 self . bits ^= other . bits ; } } impl $ crate:: __core:: ops:: BitAnd for $
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:95:59: 96:19 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:95 $ BitFlags { bits : self . bits ^ other . bits } } } impl $ crate:: __core::
<bitflags macros>:96 ops:: BitXorAssign for $ BitFlags {
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:107:15: 108:32 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:107  # [ inline ] fn bitand_assign ( & mut self , other : $ BitFlags ) {
<bitflags macros>:108 self . bits &= other . bits ; } } impl $ crate:: __core:: ops:: Sub for $
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:104:59: 105:19 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:104 $ BitFlags { bits : self . bits & other . bits } } } impl $ crate:: __core::
<bitflags macros>:105 ops:: BitAndAssign for $ BitFlags {
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:116:15: 117:34 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:116  # [ inline ] fn sub_assign ( & mut self , other : $ BitFlags ) {
<bitflags macros>:117 self . bits &= ! other . bits ; } } impl $ crate:: __core:: ops:: Not for $
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:113:61: 114:16 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:113 $ BitFlags { bits : self . bits & ! other . bits } } } impl $ crate:: __core::
<bitflags macros>:114 ops:: SubAssign for $ BitFlags {
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
error: aborting due to 8 previous errors
Build failed, waiting for other jobs to finish..
```

**Comment by nox** [comment] 2016-05-16 14:25
Sorry for this @Jayflux, see https://github.com/servo/cocoa-rs/pull/128.

Either run `rm Cargo.lock` or `cargo update -p cocoa --precise 0.3.3`.

**Comment by Jayflux** [comment] 2016-05-16 14:50
```
MC-S104347:glut willij87$ rm Cargo.lock 
MC-S104347:glut willij87$ cargo build
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading cocoa v0.3.3
   Compiling bitflags v0.3.3
   Compiling xml-rs v0.3.3
   Compiling cocoa v0.3.3
<bitflags macros>:89:15: 90:32 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:89  # [ inline ] fn bitor_assign ( & mut self , other : $ BitFlags ) {
<bitflags macros>:90 self . bits |= other . bits ; } } impl $ crate:: __core:: ops:: BitXor for $
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:86:59: 87:18 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:86 $ BitFlags { bits : self . bits | other . bits } } } impl $ crate:: __core::
<bitflags macros>:87 ops:: BitOrAssign for $ BitFlags {
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:98:15: 99:32 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:98  # [ inline ] fn bitxor_assign ( & mut self , other : $ BitFlags ) {
<bitflags macros>:99 self . bits ^= other . bits ; } } impl $ crate:: __core:: ops:: BitAnd for $
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:95:59: 96:19 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:95 $ BitFlags { bits : self . bits ^ other . bits } } } impl $ crate:: __core::
<bitflags macros>:96 ops:: BitXorAssign for $ BitFlags {
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:107:15: 108:32 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:107  # [ inline ] fn bitand_assign ( & mut self , other : $ BitFlags ) {
<bitflags macros>:108 self . bits &= other . bits ; } } impl $ crate:: __core:: ops:: Sub for $
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:104:59: 105:19 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:104 $ BitFlags { bits : self . bits & other . bits } } } impl $ crate:: __core::
<bitflags macros>:105 ops:: BitAndAssign for $ BitFlags {
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:116:15: 117:34 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:116  # [ inline ] fn sub_assign ( & mut self , other : $ BitFlags ) {
<bitflags macros>:117 self . bits &= ! other . bits ; } } impl $ crate:: __core:: ops:: Not for $
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
<bitflags macros>:113:61: 114:16 error: use of unstable library feature 'op_assign_traits': recently added (see issue #28235)
<bitflags macros>:113 $ BitFlags { bits : self . bits & ! other . bits } } } impl $ crate:: __core::
<bitflags macros>:114 ops:: SubAssign for $ BitFlags {
<bitflags macros>:17:24: 19:63 note: in this expansion of bitflags! (defined in <bitflags macros>)
/Users/willij87/.cargo/registry/src/github.com-88ac128001ac3a9a/xml-rs-0.3.3/src/writer/emitter.rs:121:1: 127:3 note: in this expansion of bitflags! (defined in <bitflags macros>)
error: aborting due to 8 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `xml-rs`.
```

**Comment by Jayflux** [comment] 2016-05-16 15:00
Updated my rust to 1.8.0 and i no longer have this issue

**Comment by nox** [comment] 2016-05-16 15:06
Given that neither xml-rs 0.3.3 nor cocoa 0.3.3 use bitflags 0.7, I think the demo has been broken for a while with Rust <1.8.

**Comment by Phlosioneer** [comment] 2016-05-24 06:34
> Given that the Assign implementations in bitflags predates bitflags 0.6, I think the demo has been broken for a while with Rust <1.8.
Is this something that needs to be fixed...? Given how fast Rust is changing, I don't see dropping support for <1.8 being a problem.

**Comment by posborne** [comment] 2016-06-22 17:30
> Is this something that needs to be fixed...? Given how fast Rust is changing, I don't see dropping support for <1.8 being a problem.

I am currently stuck on 1.7 using Yocto which I need for doing reproducible production builds for an embedded device.  We'll move that forward eventually (we actually have to patch quite a few things), but in the meantime it is a real problem.

**Comment by tomaka** [comment] 2016-11-03 08:10
Going to close this since it's fixed apparently.

**Closed by tomaka** 2016-11-03 08:10 UTC
