### ISSUE TITLE
Example Code Crash

### ISSUE THREAD

**Issue by TheOpenDevProject** [tomaka/glutin#647] opened 2015-10-26 23:17 UTC
![image](https://cloud.githubusercontent.com/assets/6072108/10745177/973aa9e2-7c93-11e5-887a-b94c0a28c161.png)

Code 

``` rust
extern crate gl;
extern crate glutin;
extern crate libc;

fn main() {
    let window = glutin::Window::new().unwrap();

    unsafe { window.make_current() };

    unsafe {
        gl::load_with(|symbol| window.get_proc_address(symbol));

        gl::ClearColor(0.0, 1.0, 0.0, 1.0);
    }

    for event in window.wait_events() {
        unsafe { gl::Clear(gl::COLOR_BUFFER_BIT) };
        window.swap_buffers();

        match event {
            glutin::Event::Closed => break,
            _ => ()
        }
    }
}
```

O/S: Windows 7 Enterprise 64bit
Rust Version: Rust 1.3 64Bit Windows (installed from MSI)

Could it be that I might not have OpenGL Supportive hardware?

**Comment by tomaka** [comment] 2015-10-27 08:18
Could you run the program in a debugger and see where exactly it crashes?

**Comment by TheOpenDevProject** [comment] 2015-11-01 12:05
I will do this tomorrow morning AEST for you. Have not had time over the weekend.

**Comment by tomaka** [comment] 2016-11-03 07:58
I'm going to close this since I don't have any information about what's happening.
Please reopen if the problem is still there and/or you have a stack trace to share.

**Closed by tomaka** 2016-11-03 07:58 UTC
Labels: A-win32
