### ISSUE TITLE
[linux] Closing windows is neither documented nor works out of the box

### ISSUE THREAD

**Issue by lspitzner** [tomaka/glutin#835] opened 2016-12-08 13:21 UTC
I currently observe the following: When closing a window it receives the close signal but remains open. Of course the redrawing stops because I cancel its loop. This happens as well when doing a `new; drop` sequence, which I had hoped would give a very quick blink of a window.

For the multiwindow example I also observe the following: Closing window C by pressing on its top-right x closes window A, and then B. Or maybe the other way around. I have not looked into the exact logic o this behaviour, but it certainly seems like events reach wrong windows. While the wrong windows receive the signal, for any but the last window the closing itself works, i.e. the window is gone. But for the last window the behaviour falls back to the above, i.e. while the loop receives a close-signal it remains on-screen.

On the chance that it has anything to do with it, I currently run the example not in the "main" thread but in a spawned thread. (In fact I create a static lib and not an executable, so I really have no idea if there exists a "main" thread.) But I would really hope that this fact was not supposed to affect the behaviour of glutin.

As this whole behaviour seems rather obscure it seems likely that the window closing is just a symptom of some other underlying issue.

I am sorry to say that I will consider different frameworks so I probably won't be willing to test this further.

**Comment by tomaka** [comment] 2016-12-08 13:29
Thanks for the report.
I suppose this is with X11, in which case I'll close as a duplicate of https://github.com/tomaka/winit/issues/79

**Closed by tomaka** 2016-12-08 13:29 UTC

**Comment by lspitzner** [comment] 2016-12-08 13:35
There are two aspects not covered by the references issue: 1) Documentation of how closing is supposed to work. 2) The behaviour in the multiple-window example.
